from flask import render_template

def fleet_efficiency_vs_fleet_efficiency_with_load_idling_graph_view():
  return render_template('analytics/fleet_efficiency_vs_fleet_efficiency_with_load_idling_graph.html')
